language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install amalg-redis
  - luarocks install busted
  - luarocks install luacheck
  - luarocks install net-url 0.9
  - luarocks install redis-lua
  - luarocks install stuart
  - luarocks make stuart-redis-0.1.0-0.rockspec

services:
  - redis-server

script:
  - luacheck --std max+busted --codes examples spec src --globals "_" redis --ignore 122 212 213 241 611 --exclude-files "**/*-with-dependencies.lua"
  - REDIS_URL=redis://localhost:6379 busted --verbose --defer-print
